"""official_db

Revision ID: 3e8252aef8c0
Revises: a8bfb216659d
Create Date: 2024-09-30 17:01:57.862900

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3e8252aef8c0'
down_revision = 'a8bfb216659d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.CHAR(length=200), nullable=False))
        batch_op.drop_column('passwort')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passwort', mysql.CHAR(length=200), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
