"""migrate-check

Revision ID: a8bfb216659d
Revises: 
Create Date: 2024-09-30 16:51:24.313093

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8bfb216659d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passwort', sa.CHAR(length=200), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.CHAR(length=200), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('passwort')

    # ### end Alembic commands ###
